apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/d-srinath/argocd-project.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
